### ISSUE TITLE
Add support for HTTP Headers

### ISSUE THREAD

**Issue by OuiSouss** [dhenry123/utdon#18]
Hello, 

First of all, I'd like to thank you for this very useful tool.

I've just tested the tool a little. I have the impression that it's not possible to set HTTP headers to query the production URL.

For example, I have a TrueNas Scale at home and to get its version, it is necessary to use HTTP API with HTTP header Authorization.

Did I miss something or is it a real request feature ?

**Comment by luclu7** [comment]
Hello, I don't think it's currently possible. It could be added, if you can!

**Comment by dhenry123** [comment]
Thank you for your interest,
Your request has been accepted and will be available soon.
+++

**Comment by dhenry123** [comment]
Hello @OuiSouss 

Hello, what type of deployment are you using, legacy or container? I'd like to prepare a pre-release that you could test (there will be no impact on your current data).
Do you agree?

I need to do some testing, so I think it'll be ready the day after tomorrow.
+++

![image](https://github.com/dhenry123/utdon/assets/27366357/93023612-9baf-4925-87d4-1bd3efde57ee)

**Comment by OuiSouss** [comment]
Thanks a lot (sorry I did not see the message). It's perfect, I will update the container.

**Comment by dhenry123** [comment]
Thanks for the feedback!

**Comment by dhenry123** [comment]
Hi @OuiSouss 
I'm using this feature for the first time to check the version of dataplane haproxy API, which requires authentication.
When the new control was created, the version request was OK. Once the control had been saved, I clicked on the "compare" button and got a 401 error.
After checking my code, the method responsible for making the comparison does not implement the authentication header.
I'm in the process of fixing it, and a new version will be available soon.
+++
